# Generated by Django 5.1.1 on 2024-11-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('link', models.CharField(max_length=150, null=True)),
                ('posted_date', models.DateField(null=True)),
            ],
        ),
    ]
