# Generated by Django 5.1.1 on 2024-11-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=40, null=True)),
                ('city_pic', models.ImageField(null=True, upload_to='static/city_news/')),
            ],
        ),
        migrations.CreateModel(
            name='vdo_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdo_headline', models.CharField(max_length=400, null=True)),
                ('vdo_news_descrp', models.TextField(null=True)),
                ('vdo_link', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=400, null=True)),
                ('news_descrp', models.TextField(null=True)),
                ('posted_date', models.DateField()),
                ('news_pic', models.ImageField(null=True, upload_to='static/news/')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('news_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city_news')),
            ],
        ),
    ]
