# Generated by Django 5.1.1 on 2024-11-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_city_news_vdo_news_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='link',
            new_name='jlink',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='posted_date',
            new_name='jposted_date',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='title',
            new_name='jtitle',
        ),
    ]
